m1 = int(input('Digite o valor da 1ª massa: '))
m2 = int(input('Digite o valor da 2ª massa: '))
m3 = int(input('Digite o valor da 3ª massa: '))
r12 = int(input('Digite o valor da distância r12: '))
r13 = int(input('Digite o valor da distância r13: '))
r23 = int(input('Digite o valor da distância r23: '))
G = 6.67 * (10** - 11)
F = G *((m1 * m2) / r12 ** 2 + (m1 * m3) / r13 ** 2 + (m2 * m3) / r23 ** 2)
print(f'Força de coesão: {F} N')
